import os
import django
import requests
import json

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from complaints.models import Province, District, Municipality, Ward

# =====================
# NEPAL FULL DATA
# 7 Provinces, 77 Districts, 753 Municipalities
# =====================

data = {
    "Koshi Province": {
        "name_np": "कोशी प्रदेश",
        "districts": {
            "Taplejung": {"name_np": "ताप्लेजुङ", "municipalities": [
                ("Phungling Municipality", "फुङलिङ नगरपालिका", "municipality", 9),
                ("Sidingba Rural Municipality", "सिदिङ्वा गाउँपालिका", "rural", 6),
                ("Mikwakhola Rural Municipality", "मिक्वाखोला गाउँपालिका", "rural", 5),
                ("Meringden Rural Municipality", "मेरिङदेन गाउँपालिका", "rural", 5),
                ("Maiwakhola Rural Municipality", "मैवाखोला गाउँपालिका", "rural", 5),
                ("Pathivara Yangwarak Rural Municipality", "पाथीभरा याङवरक गाउँपालिका", "rural", 7),
                ("Sirijunga Rural Municipality", "सिरीजङ्घा गाउँपालिका", "rural", 6),
                ("Phaktanglung Rural Municipality", "फक्ताङलुङ गाउँपालिका", "rural", 6),
                ("Aathrai Tribeni Rural Municipality", "आठराई त्रिवेणी गाउँपालिका", "rural", 9),
            ]},
            "Panchthar": {"name_np": "पाँचथर", "municipalities": [
                ("Phidim Municipality", "फिदिम नगरपालिका", "municipality", 9),
                ("Falgunanda Rural Municipality", "फाल्गुनन्द गाउँपालिका", "rural", 6),
                ("Hilihang Rural Municipality", "हिलिहाङ गाउँपालिका", "rural", 7),
                ("Kummayak Rural Municipality", "कुम्माई गाउँपालिका", "rural", 6),
                ("Miklajung Rural Municipality", "मिक्लाजुङ गाउँपालिका", "rural", 6),
                ("Tumbewa Rural Municipality", "तुम्बेवा गाउँपालिका", "rural", 6),
                ("Yangwarak Rural Municipality", "याङवरक गाउँपालिका", "rural", 6),
            ]},
            "Ilam": {"name_np": "इलाम", "municipalities": [
                ("Ilam Municipality", "इलाम नगरपालिका", "municipality", 9),
                ("Deumai Municipality", "देउमाई नगरपालिका", "municipality", 9),
                ("Mai Municipality", "माई नगरपालिका", "municipality", 9),
                ("Suryodaya Municipality", "सूर्योदय नगरपालिका", "municipality", 9),
                ("Chulachuli Rural Municipality", "चुलाचुली गाउँपालिका", "rural", 6),
                ("Fakfokthum Rural Municipality", "फाकफोकथुम गाउँपालिका", "rural", 6),
                ("Maijogmai Rural Municipality", "माईजोगमाई गाउँपालिका", "rural", 6),
                ("Mangsebung Rural Municipality", "माङसेबुङ गाउँपालिका", "rural", 6),
                ("Rong Rural Municipality", "रोङ गाउँपालिका", "rural", 6),
                ("Sandakpur Rural Municipality", "सन्दकपुर गाउँपालिका", "rural", 6),
            ]},
            "Jhapa": {"name_np": "झापा", "municipalities": [
                ("Mechinagar Municipality", "मेची नगर नगरपालिका", "municipality", 9),
                ("Birtamode Municipality", "बिर्तामोड नगरपालिका", "municipality", 9),
                ("Damak Municipality", "दमक नगरपालिका", "municipality", 9),
                ("Kankai Municipality", "कन्काई नगरपालिका", "municipality", 9),
                ("Arjundhara Municipality", "अर्जुनधारा नगरपालिका", "municipality", 9),
                ("Shivasataxi Municipality", "शिवसताक्षी नगरपालिका", "municipality", 9),
                ("Gauradaha Municipality", "गौरादह नगरपालिका", "municipality", 9),
                ("Bhadrapur Municipality", "भद्रपुर नगरपालिका", "municipality", 9),
                ("Haldibari Rural Municipality", "हल्दिबारी गाउँपालिका", "rural", 6),
                ("Kamal Rural Municipality", "कमल गाउँपालिका", "rural", 7),
                ("Kechanakawl Rural Municipality", "केचनाकवल गाउँपालिका", "rural", 7),
                ("Jhapa Rural Municipality", "झापा गाउँपालिका", "rural", 6),
                ("Buddhasanti Rural Municipality", "बुद्धशान्ति गाउँपालिका", "rural", 7),
                ("Barhadashi Rural Municipality", "बाह्रदशी गाउँपालिका", "rural", 7),
            ]},
            "Morang": {"name_np": "मोरङ", "municipalities": [
                ("Biratnagar Metropolitan City", "विराटनगर महानगरपालिका", "metropolitan", 19),
                ("Urlabari Municipality", "उर्लाबारी नगरपालिका", "municipality", 9),
                ("Belbari Municipality", "बेलबारी नगरपालिका", "municipality", 9),
                ("Letang Municipality", "लेटाङ नगरपालिका", "municipality", 9),
                ("Pathari Shanischare Municipality", "पथरी शनिश्चरे नगरपालिका", "municipality", 9),
                ("Rangeli Municipality", "रङेली नगरपालिका", "municipality", 9),
                ("Sundarharaicha Municipality", "सुन्दरहरैचा नगरपालिका", "municipality", 9),
                ("Jahada Rural Municipality", "जहदा गाउँपालिका", "rural", 6),
                ("Katahari Rural Municipality", "कटहरी गाउँपालिका", "rural", 7),
                ("Kerabari Rural Municipality", "केराबारी गाउँपालिका", "rural", 6),
                ("Gramthan Rural Municipality", "ग्रामथान गाउँपालिका", "rural", 6),
                ("Budhiganga Rural Municipality", "बुढीगंगा गाउँपालिका", "rural", 6),
                ("Miklajung Rural Municipality", "मिक्लाजुङ गाउँपालिका", "rural", 6),
                ("Kanepokhari Rural Municipality", "कानेपोखरी गाउँपालिका", "rural", 6),
            ]},
            "Sunsari": {"name_np": "सुनसरी", "municipalities": [
                ("Dharan Sub-Metropolitan City", "धरान उपमहानगरपालिका", "sub_metropolitan", 19),
                ("Inaruwa Municipality", "इनरुवा नगरपालिका", "municipality", 9),
                ("Itahari Sub-Metropolitan City", "इटहरी उपमहानगरपालिका", "sub_metropolitan", 11),
                ("Duhabi Municipality", "दुहबी नगरपालिका", "municipality", 9),
                ("Ramdhuni Municipality", "रामधुनी नगरपालिका", "municipality", 9),
                ("Barahachhetra Municipality", "बराहक्षेत्र नगरपालिका", "municipality", 9),
                ("Bhokraha Narsingh Rural Municipality", "भोक्राहा नरसिंह गाउँपालिका", "rural", 7),
                ("Dewangunj Rural Municipality", "देवानगञ्ज गाउँपालिका", "rural", 6),
                ("Gadhi Rural Municipality", "गढी गाउँपालिका", "rural", 6),
                ("Harinagara Rural Municipality", "हरिनगरा गाउँपालिका", "rural", 6),
                ("Koshi Rural Municipality", "कोशी गाउँपालिका", "rural", 6),
            ]},
            "Dhankuta": {"name_np": "धनकुटा", "municipalities": [
                ("Dhankuta Municipality", "धनकुटा नगरपालिका", "municipality", 9),
                ("Pakhribas Municipality", "पाख्रिबास नगरपालिका", "municipality", 9),
                ("Mahalaxmi Municipality", "महालक्ष्मी नगरपालिका", "municipality", 9),
                ("Chhathar Jorpati Rural Municipality", "छथर जोरपाटी गाउँपालिका", "rural", 6),
                ("Sahidbhumi Rural Municipality", "सहिदभूमि गाउँपालिका", "rural", 6),
                ("Sangurigadhi Rural Municipality", "साँगुरीगढी गाउँपालिका", "rural", 5),
                ("Kharandi Rural Municipality", "खाँडबारी गाउँपालिका", "rural", 6),
            ]},
            "Terhathum": {"name_np": "तेह्रथुम", "municipalities": [
                ("Myanglung Municipality", "म्याङलुङ नगरपालिका", "municipality", 9),
                ("Laligurans Municipality", "लालीगुराँस नगरपालिका", "municipality", 9),
                ("Aathrai Rural Municipality", "आठराई गाउँपालिका", "rural", 6),
                ("Chhathar Rural Municipality", "छथर गाउँपालिका", "rural", 5),
                ("Menchyayem Rural Municipality", "मेन्छयायेम गाउँपालिका", "rural", 5),
                ("Phedap Rural Municipality", "फेदाप गाउँपालिका", "rural", 7),
            ]},
            "Sankhuwasabha": {"name_np": "सङ्खुवासभा", "municipalities": [
                ("Khandbari Municipality", "खाँडबारी नगरपालिका", "municipality", 9),
                ("Dharmadevi Municipality", "धर्मदेवी नगरपालिका", "municipality", 9),
                ("Panchkhapan Municipality", "पाँचखपन नगरपालिका", "municipality", 9),
                ("Madi Municipality", "मादी नगरपालिका", "municipality", 9),
                ("Chichila Rural Municipality", "चिचिला गाउँपालिका", "rural", 6),
                ("Makalu Rural Municipality", "मकालु गाउँपालिका", "rural", 6),
                ("Sabhapokhari Rural Municipality", "सभापोखरी गाउँपालिका", "rural", 6),
                ("Silichong Rural Municipality", "सिलिचोङ गाउँपालिका", "rural", 6),
                ("Bhotkhola Rural Municipality", "भोटखोला गाउँपालिका", "rural", 5),
            ]},
            "Bhojpur": {"name_np": "भोजपुर", "municipalities": [
                ("Bhojpur Municipality", "भोजपुर नगरपालिका", "municipality", 9),
                ("Shadananda Municipality", "षडानन्द नगरपालिका", "municipality", 9),
                ("Arun Rural Municipality", "अरुण गाउँपालिका", "rural", 6),
                ("Hatuwagadhi Rural Municipality", "हतुवागढी गाउँपालिका", "rural", 6),
                ("Pauwadungma Rural Municipality", "पौवादुङमा गाउँपालिका", "rural", 6),
                ("Ramprasad Rai Rural Municipality", "रामप्रसाद राई गाउँपालिका", "rural", 5),
                ("Salpasilichho Rural Municipality", "साल्पासिलिचो गाउँपालिका", "rural", 6),
                ("Tyamke Yuwa Rural Municipality", "त्याम्के युवा गाउँपालिका", "rural", 5),
            ]},
            "Solukhumbu": {"name_np": "सोलुखुम्बु", "municipalities": [
                ("Solu Dudhkunda Municipality", "सोलु दुधकुण्ड नगरपालिका", "municipality", 9),
                ("Thulung Dudhkoshi Rural Municipality", "थुलुङ दुधकोशी गाउँपालिका", "rural", 7),
                ("Likhupike Rural Municipality", "लिखुपिके गाउँपालिका", "rural", 6),
                ("Mahakulung Rural Municipality", "महाकुलुङ गाउँपालिका", "rural", 7),
                ("Khumbu Pasanglhamu Rural Municipality", "खुम्बु पासाङल्हामु गाउँपालिका", "rural", 5),
                ("Sotang Rural Municipality", "सोताङ गाउँपालिका", "rural", 6),
                ("Mapya Dudhkoshi Rural Municipality", "माप्य दुधकोशी गाउँपालिका", "rural", 6),
            ]},
            "Okhaldhunga": {"name_np": "ओखलढुङ्गा", "municipalities": [
                ("Siddhicharan Municipality", "सिद्धिचरण नगरपालिका", "municipality", 9),
                ("Molung Rural Municipality", "मोलुङ गाउँपालिका", "rural", 6),
                ("Champadevi Rural Municipality", "चम्पादेवी गाउँपालिका", "rural", 6),
                ("Khijidemba Rural Municipality", "खिजिदेम्बा गाउँपालिका", "rural", 6),
                ("Likhila Rural Municipality", "लिखु गाउँपालिका", "rural", 5),
                ("Manebhanjyang Rural Municipality", "मानेभञ्ज्याङ गाउँपालिका", "rural", 6),
                ("Sunkoshi Rural Municipality", "सुनकोशी गाउँपालिका", "rural", 6),
            ]},
            "Khotang": {"name_np": "खोटाङ", "municipalities": [
                ("Diktel Rupakot Majhuwagadhi Municipality", "दिक्तेल रुपाकोट मझुवागढी नगरपालिका", "municipality", 9),
                ("Halesi Tuwachung Municipality", "हलेसी तुवाचुङ नगरपालिका", "municipality", 9),
                ("Khotehang Rural Municipality", "खोटेहाङ गाउँपालिका", "rural", 6),
                ("Aiselukharka Rural Municipality", "ऐसेलुखर्का गाउँपालिका", "rural", 6),
                ("Barahapokhari Rural Municipality", "बाह्रपोखरी गाउँपालिका", "rural", 6),
                ("Diprung Chuichumma Rural Municipality", "दिप्रुङ चुइचुम्मा गाउँपालिका", "rural", 7),
                ("Jantedhunga Rural Municipality", "जन्तेढुंगा गाउँपालिका", "rural", 6),
                ("Kepilasgadhi Rural Municipality", "केपिलासगढी गाउँपालिका", "rural", 5),
                ("Rawabesi Rural Municipality", "रावाबेसी गाउँपालिका", "rural", 6),
                ("Sakela Rural Municipality", "साकेला गाउँपालिका", "rural", 6),
            ]},
            "Udayapur": {"name_np": "उदयपुर", "municipalities": [
                ("Triyuga Municipality", "त्रियुगा नगरपालिका", "municipality", 14),
                ("Udayapurgadhi Rural Municipality", "उदयपुरगढी गाउँपालिका", "rural", 6),
                ("Katari Municipality", "कटारी नगरपालिका", "municipality", 9),
                ("Chaudandigadhi Municipality", "चौदण्डीगढी नगरपालिका", "municipality", 9),
                ("Belaka Municipality", "बेलका नगरपालिका", "municipality", 9),
                ("Rautamai Rural Municipality", "रौतामाई गाउँपालिका", "rural", 6),
                ("Sunkoshi Rural Municipality", "सुनकोशी गाउँपालिका", "rural", 6),
                ("Tapli Rural Municipality", "ताप्ली गाउँपालिका", "rural", 6),
            ]},
        }
    },
    "Madhesh Province": {
        "name_np": "मधेश प्रदेश",
        "districts": {
            "Saptari": {"name_np": "सप्तरी", "municipalities": [
                ("Rajbiraj Municipality", "राजविराज नगरपालिका", "municipality", 9),
                ("Kanchanrup Municipality", "कञ्चनरूप नगरपालिका", "municipality", 9),
                ("Dakneshwori Municipality", "दक्नेश्वरी नगरपालिका", "municipality", 9),
                ("Shambhunath Municipality", "शम्भुनाथ नगरपालिका", "municipality", 9),
                ("Saptakoshi Rural Municipality", "सप्तकोशी गाउँपालिका", "rural", 6),
                ("Hanumannagar Kankalini Municipality", "हनुमाननगर कङ्कालिनी नगरपालिका", "municipality", 9),
                ("Rupani Rural Municipality", "रुपनी गाउँपालिका", "rural", 6),
                ("Chhinnamasta Rural Municipality", "छिन्नमस्ता गाउँपालिका", "rural", 6),
                ("Tirhut Rural Municipality", "तिरहुत गाउँपालिका", "rural", 6),
                ("Mahadeva Rural Municipality", "महादेवा गाउँपालिका", "rural", 7),
                ("Belhi Chapena Rural Municipality", "बेल्ही चपेना गाउँपालिका", "rural", 6),
                ("Balan Bihul Rural Municipality", "बलान-बिहुल गाउँपालिका", "rural", 6),
                ("Agnisair Krishna Savaran Rural Municipality", "अग्निसाइर कृष्णासवरन गाउँपालिका", "rural", 6),
            ]},
            "Siraha": {"name_np": "सिरहा", "municipalities": [
                ("Siraha Municipality", "सिरहा नगरपालिका", "municipality", 9),
                ("Lahan Municipality", "लहान नगरपालिका", "municipality", 9),
                ("Golbazar Municipality", "गोलबजार नगरपालिका", "municipality", 9),
                ("Mirchaiya Municipality", "मिर्चैया नगरपालिका", "municipality", 9),
                ("Dhangadhimai Municipality", "धनगढीमाई नगरपालिका", "municipality", 9),
                ("Sukhipur Municipality", "सुखिपुर नगरपालिका", "municipality", 9),
                ("Karjanha Rural Municipality", "कर्जन्हा गाउँपालिका", "rural", 6),
                ("Nawarajpur Rural Municipality", "नवराजपुर गाउँपालिका", "rural", 6),
                ("Bishnupur Rural Municipality", "विष्णुपुर गाउँपालिका", "rural", 6),
                ("Bhagawanpur Rural Municipality", "भगवानपुर गाउँपालिका", "rural", 6),
                ("Arnama Rural Municipality", "अर्नमा गाउँपालिका", "rural", 6),
                ("Bariyarpatti Rural Municipality", "बरियारपट्टी गाउँपालिका", "rural", 6),
                ("Sakhuwanankarkatti Rural Municipality", "सखुवानान्कारकट्टी गाउँपालिका", "rural", 5),
                ("Aurahi Rural Municipality", "औराही गाउँपालिका", "rural", 6),
            ]},
            "Dhanusha": {"name_np": "धनुषा", "municipalities": [
                ("Janakpur Sub-Metropolitan City", "जनकपुर उपमहानगरपालिका", "sub_metropolitan", 17),
                ("Dhanusha Rural Municipality", "धनुषा गाउँपालिका", "rural", 6),
                ("Ganeshman Charnath Municipality", "गणेशमान चारनाथ नगरपालिका", "municipality", 9),
                ("Chhireshwornath Municipality", "छिरेश्वरनाथ नगरपालिका", "municipality", 9),
                ("Mithila Municipality", "मिथिला नगरपालिका", "municipality", 9),
                ("Bideha Municipality", "विदेह नगरपालिका", "municipality", 9),
                ("Nagarain Municipality", "नगराइन नगरपालिका", "municipality", 9),
                ("Hansapur Municipality", "हंसपुर नगरपालिका", "municipality", 9),
                ("Mithila Bihari Municipality", "मिथिला बिहारी नगरपालिका", "municipality", 9),
                ("Sabaila Municipality", "सबैला नगरपालिका", "municipality", 9),
                ("Dhanushadham Rural Municipality", "धनुषाधाम गाउँपालिका", "rural", 6),
                ("Bateshwar Rural Municipality", "बटेश्वर गाउँपालिका", "rural", 6),
                ("Lakshminiya Rural Municipality", "लक्ष्मीनिया गाउँपालिका", "rural", 6),
                ("Aaurahi Rural Municipality", "औरही गाउँपालिका", "rural", 6),
                ("Mukhiyapatti Musharniya Rural Municipality", "मुखियापट्टी मुशहर्निया गाउँपालिका", "rural", 7),
                ("Kamala Rural Municipality", "कमला गाउँपालिका", "rural", 6),
                ("Janaknandini Rural Municipality", "जनकनन्दिनी गाउँपालिका", "rural", 6),
                ("Dhanauji Rural Municipality", "धनौजी गाउँपालिका", "rural", 6),
            ]},
            "Mahottari": {"name_np": "महोत्तरी", "municipalities": [
                ("Jaleshwar Municipality", "जलेश्वर नगरपालिका", "municipality", 9),
                ("Bardibas Municipality", "बर्दिबास नगरपालिका", "municipality", 9),
                ("Gaushala Municipality", "गौशाला नगरपालिका", "municipality", 9),
                ("Bhangaha Municipality", "भंगाहा नगरपालिका", "municipality", 9),
                ("Matihani Municipality", "मटिहानी नगरपालिका", "municipality", 9),
                ("Ramgopalpur Municipality", "रामगोपालपुर नगरपालिका", "municipality", 9),
                ("Manara Siswa Municipality", "मनरा शिसवा नगरपालिका", "municipality", 9),
                ("Aurahi Rural Municipality", "औराही गाउँपालिका", "rural", 6),
                ("Balawa Rural Municipality", "बलवा गाउँपालिका", "rural", 7),
                ("Ekdara Rural Municipality", "एकडारा गाउँपालिका", "rural", 6),
                ("Mahottari Rural Municipality", "महोत्तरी गाउँपालिका", "rural", 6),
                ("Pipra Rural Municipality", "पिपरा गाउँपालिका", "rural", 6),
                ("Samsi Rural Municipality", "सांसी गाउँपालिका", "rural", 5),
                ("Sonama Rural Municipality", "सोनमा गाउँपालिका", "rural", 6),
            ]},
            "Sarlahi": {"name_np": "सर्लाही", "municipalities": [
                ("Malangawa Municipality", "मलङ्गवा नगरपालिका", "municipality", 9),
                ("Haripur Municipality", "हरिपुर नगरपालिका", "municipality", 9),
                ("Lalbandi Municipality", "लालबन्दी नगरपालिका", "municipality", 9),
                ("Haripurwa Municipality", "हरिपुर्वा नगरपालिका", "municipality", 9),
                ("Ishworpur Municipality", "ईश्वरपुर नगरपालिका", "municipality", 9),
                ("Baudhimai Municipality", "बौधीमाई नगरपालिका", "municipality", 9),
                ("Balara Municipality", "बलरा नगरपालिका", "municipality", 9),
                ("Godaita Municipality", "गोडैटा नगरपालिका", "municipality", 9),
                ("Chakraghatta Rural Municipality", "चक्रघट्टा गाउँपालिका", "rural", 6),
                ("Bishnu Rural Municipality", "विष्णु गाउँपालिका", "rural", 6),
                ("Bramhapuri Rural Municipality", "ब्रह्मपुरी गाउँपालिका", "rural", 6),
                ("Dhankaul Rural Municipality", "धनकौल गाउँपालिका", "rural", 7),
                ("Kabilasi Rural Municipality", "कविलासी गाउँपालिका", "rural", 7),
                ("Ramnagar Rural Municipality", "रामनगर गाउँपालिका", "rural", 6),
                ("Basbariya Rural Municipality", "बसबरिया गाउँपालिका", "rural", 6),
                ("Parwanipur Rural Municipality", "पर्वानीपुर गाउँपालिका", "rural", 6),
                ("Harthawa Rural Municipality", "हर्तावा गाउँपालिका", "rural", 6),
            ]},
            "Rautahat": {"name_np": "रौतहट", "municipalities": [
                ("Gaur Municipality", "गौर नगरपालिका", "municipality", 9),
                ("Chandrapur Municipality", "चन्द्रपुर नगरपालिका", "municipality", 9),
                ("Garuda Municipality", "गरुडा नगरपालिका", "municipality", 9),
                ("Gadhimai Municipality", "गढीमाई नगरपालिका", "municipality", 9),
                ("Katahariya Municipality", "कटहरिया नगरपालिका", "municipality", 9),
                ("Baudhimai Municipality", "बौधीमाई नगरपालिका", "municipality", 9),
                ("Brindaban Municipality", "वृन्दावन नगरपालिका", "municipality", 9),
                ("Maulapur Municipality", "मौलापुर नगरपालिका", "municipality", 9),
                ("Rajpur Municipality", "राजपुर नगरपालिका", "municipality", 9),
                ("Paroha Municipality", "परोहा नगरपालिका", "municipality", 9),
                ("Devahi Gonahi Rural Municipality", "देवाही गोनाही गाउँपालिका", "rural", 7),
                ("Durga Bhagwati Rural Municipality", "दुर्गाभगवती गाउँपालिका", "rural", 6),
                ("Ishanath Rural Municipality", "ईशनाथ गाउँपालिका", "rural", 6),
                ("Madhav Narayan Rural Municipality", "माधवनारायण गाउँपालिका", "rural", 7),
                ("Phatuwa Bijayapur Rural Municipality", "फतुवा बिजयपुर गाउँपालिका", "rural", 7),
                ("Rajdevi Rural Municipality", "राजदेवी गाउँपालिका", "rural", 6),
                ("Yamunamai Rural Municipality", "यमुनामाई गाउँपालिका", "rural", 6),
            ]},
            "Bara": {"name_np": "बारा", "municipalities": [
                ("Kalaiya Sub-Metropolitan City", "कलैया उपमहानगरपालिका", "sub_metropolitan", 16),
                ("Jeetpur Simara Sub-Metropolitan City", "जीतपुर सिमरा उपमहानगरपालिका", "sub_metropolitan", 15),
                ("Kolhabi Municipality", "कोल्हवी नगरपालिका", "municipality", 9),
                ("Nijgadh Municipality", "निजगढ नगरपालिका", "municipality", 9),
                ("Mahagadhimai Municipality", "महागढीमाई नगरपालिका", "municipality", 9),
                ("Prasauni Municipality", "प्रसौनी नगरपालिका", "municipality", 9),
                ("Devtal Rural Municipality", "देवताल गाउँपालिका", "rural", 6),
                ("Adarsha Kotwal Rural Municipality", "आदर्श कोटवाल गाउँपालिका", "rural", 6),
                ("Pheta Rural Municipality", "फेटा गाउँपालिका", "rural", 6),
                ("Bishrampur Rural Municipality", "विश्रामपुर गाउँपालिका", "rural", 6),
                ("Karaiyamai Rural Municipality", "करैयामाई गाउँपालिका", "rural", 6),
                ("Suwarna Rural Municipality", "सुवर्ण गाउँपालिका", "rural", 6),
                ("Simraungadh Rural Municipality", "सिम्रौनगढ गाउँपालिका", "rural", 6),
            ]},
            "Parsa": {"name_np": "पर्सा", "municipalities": [
                ("Birgunj Metropolitan City", "वीरगञ्ज महानगरपालिका", "metropolitan", 32),
                ("Bahudarmai Municipality", "बहुदरमाई नगरपालिका", "municipality", 9),
                ("Pokhariya Municipality", "पोखरिया नगरपालिका", "municipality", 9),
                ("Parsagadhi Municipality", "पर्सागढी नगरपालिका", "municipality", 9),
                ("Chhipaharmai Municipality", "छिपहरमाई नगरपालिका", "municipality", 9),
                ("Bindabasini Rural Municipality", "विन्दबासिनी गाउँपालिका", "rural", 6),
                ("Dhobini Rural Municipality", "ढोलबाहा गाउँपालिका", "rural", 6),
                ("Jagarnathpur Rural Municipality", "जगरनाथपुर गाउँपालिका", "rural", 6),
                ("Kalikamai Rural Municipality", "कालिकामाई गाउँपालिका", "rural", 6),
                ("Paterwa Sugauli Rural Municipality", "पटेरवा सुगौली गाउँपालिका", "rural", 7),
                ("Pkhariya Rural Municipality", "पखरौली गाउँपालिका", "rural", 6),
                ("Sakhuwa Prasauni Rural Municipality", "सखुवा प्रसौनी गाउँपालिका", "rural", 6),
                ("Thori Rural Municipality", "ठोरी गाउँपालिका", "rural", 6),
            ]},
        }
    },
    "Bagmati Province": {
        "name_np": "बागमती प्रदेश",
        "districts": {
            "Kathmandu": {"name_np": "काठमाडौँ", "municipalities": [
                ("Kathmandu Metropolitan City", "काठमाडौँ महानगरपालिका", "metropolitan", 32),
                ("Kirtipur Municipality", "कीर्तिपुर नगरपालिका", "municipality", 10),
                ("Budhanilkantha Municipality", "बुढानीलकण्ठ नगरपालिका", "municipality", 13),
                ("Kageshwori Manohara Municipality", "कागेश्वरी मनोहरा नगरपालिका", "municipality", 9),
                ("Gokarneshwor Municipality", "गोकर्णेश्वर नगरपालिका", "municipality", 9),
                ("Tarakeshwor Municipality", "तारकेश्वर नगरपालिका", "municipality", 11),
                ("Tokha Municipality", "टोखा नगरपालिका", "municipality", 11),
                ("Chandragiri Municipality", "चन्द्रागिरि नगरपालिका", "municipality", 15),
                ("Dakshinkali Municipality", "दक्षिणकाली नगरपालिका", "municipality", 11),
                ("Nagarjun Municipality", "नागार्जुन नगरपालिका", "municipality", 10),
                ("Shankharapur Municipality", "शङ्खरापुर नगरपालिका", "municipality", 9),
            ]},
            "Lalitpur": {"name_np": "ललितपुर", "municipalities": [
                ("Lalitpur Metropolitan City", "ललितपुर महानगरपालिका", "metropolitan", 29),
                ("Godawari Municipality", "गोदावरी नगरपालिका", "municipality", 14),
                ("Mahalaxmi Municipality", "महालक्ष्मी नगरपालिका", "municipality", 11),
                ("Bagmati Rural Municipality", "बागमती गाउँपालिका", "rural", 5),
                ("Konjyosom Rural Municipality", "कोन्ज्योसोम गाउँपालिका", "rural", 5),
            ]},
            "Bhaktapur": {"name_np": "भक्तपुर", "municipalities": [
                ("Bhaktapur Municipality", "भक्तपुर नगरपालिका", "municipality", 10),
                ("Madhyapur Thimi Municipality", "मध्यपुर थिमि नगरपालिका", "municipality", 7),
                ("Changunarayan Municipality", "चाँगुनारायण नगरपालिका", "municipality", 9),
                ("Suryabinayak Municipality", "सूर्यबिनायक नगरपालिका", "municipality", 8),
            ]},
            "Kavrepalanchok": {"name_np": "काभ्रेपलाञ्चोक", "municipalities": [
                ("Dhulikhel Municipality", "धुलिखेल नगरपालिका", "municipality", 9),
                ("Banepa Municipality", "बनेपा नगरपालिका", "municipality", 9),
                ("Panauti Municipality", "पनौती नगरपालिका", "municipality", 9),
                ("Mandandeupur Municipality", "मण्डनदेउपुर नगरपालिका", "municipality", 9),
                ("Namobuddha Municipality", "नमोबुद्ध नगरपालिका", "municipality", 9),
                ("Panchkhal Municipality", "पाँचखाल नगरपालिका", "municipality", 9),
                ("Khanikhola Rural Municipality", "खानीखोला गाउँपालिका", "rural", 6),
                ("Bhumlu Rural Municipality", "भूमलु गाउँपालिका", "rural", 7),
                ("Chaurideurali Rural Municipality", "चौरीदेउराली गाउँपालिका", "rural", 6),
                ("Mahabharat Rural Municipality", "महाभारत गाउँपालिका", "rural", 6),
                ("Roshi Rural Municipality", "रोशी गाउँपालिका", "rural", 6),
                ("Temal Rural Municipality", "तेमाल गाउँपालिका", "rural", 6),
            ]},
            "Chitwan": {"name_np": "चितवन", "municipalities": [
                ("Bharatpur Metropolitan City", "भरतपुर महानगरपालिका", "metropolitan", 29),
                ("Ratnanagar Municipality", "रत्ननगर नगरपालिका", "municipality", 14),
                ("Khairahani Municipality", "खैरहनी नगरपालिका", "municipality", 9),
                ("Madi Municipality", "माडी नगरपालिका", "municipality", 9),
                ("Rapti Municipality", "राप्ती नगरपालिका", "municipality", 9),
                ("Ichchhakamana Rural Municipality", "इच्छाकामना गाउँपालिका", "rural", 6),
            ]},
            "Makwanpur": {"name_np": "मकवानपुर", "municipalities": [
                ("Hetauda Sub-Metropolitan City", "हेटौंडा उपमहानगरपालिका", "sub_metropolitan", 16),
                ("Thaha Municipality", "थाहा नगरपालिका", "municipality", 9),
                ("Bhimphedi Rural Municipality", "भीमफेदी गाउँपालिका", "rural", 6),
                ("Bakaiya Rural Municipality", "बकैया गाउँपालिका", "rural", 6),
                ("Bagmati Rural Municipality", "बागमती गाउँपालिका", "rural", 6),
                ("Kailash Rural Municipality", "कैलाश गाउँपालिका", "rural", 6),
                ("Indrasarowar Rural Municipality", "इन्द्रसरोवर गाउँपालिका", "rural", 5),
                ("Manahari Rural Municipality", "मनहरी गाउँपालिका", "rural", 7),
                ("Makawanpurgadhi Rural Municipality", "मकवानपुरगढी गाउँपालिका", "rural", 6),
                ("Raksirang Rural Municipality", "राक्सिराङ गाउँपालिका", "rural", 8),
            ]},
            "Rasuwa": {"name_np": "रसुवा", "municipalities": [
                ("Uttargaya Rural Municipality", "उत्तरगया गाउँपालिका", "rural", 5),
                ("Aamachhodingmo Rural Municipality", "आमाछोदिङमो गाउँपालिका", "rural", 5),
                ("Gosaikunda Rural Municipality", "गोसाईकुण्ड गाउँपालिका", "rural", 6),
                ("Kalika Rural Municipality", "कालिका गाउँपालिका", "rural", 5),
                ("Naukunda Rural Municipality", "नौकुण्ड गाउँपालिका", "rural", 5),
            ]},
            "Nuwakot": {"name_np": "नुवाकोट", "municipalities": [
                ("Bidur Municipality", "बिदुर नगरपालिका", "municipality", 11),
                ("Belkotgadhi Municipality", "बेलकोटगढी नगरपालिका", "municipality", 9),
                ("Kakani Rural Municipality", "ककानी गाउँपालिका", "rural", 7),
                ("Kispang Rural Municipality", "किस्पाङ गाउँपालिका", "rural", 7),
                ("Myagang Rural Municipality", "म्याङ गाउँपालिका", "rural", 7),
                ("Shivapuri Rural Municipality", "शिवपुरी गाउँपालिका", "rural", 6),
                ("Panchakanya Rural Municipality", "पञ्चकन्या गाउँपालिका", "rural", 6),
                ("Suryagadhi Rural Municipality", "सूर्यगढी गाउँपालिका", "rural", 7),
                ("Likhu Rural Municipality", "लिखु गाउँपालिका", "rural", 6),
                ("Tadi Rural Municipality", "तादी गाउँपालिका", "rural", 6),
                ("Tarkeshwar Rural Municipality", "तारकेश्वर गाउँपालिका", "rural", 6),
                ("Dupcheshwar Rural Municipality", "दुप्चेश्वर गाउँपालिका", "rural", 7),
            ]},
            "Dhading": {"name_np": "धादिङ", "municipalities": [
                ("Nilkantha Municipality", "नीलकण्ठ नगरपालिका", "municipality", 15),
                ("Benighat Rorang Rural Municipality", "बेनीघाट रोराङ गाउँपालिका", "rural", 7),
                ("Gajuri Rural Municipality", "गजुरी गाउँपालिका", "rural", 7),
                ("Galchi Rural Municipality", "गल्छी गाउँपालिका", "rural", 7),
                ("Gangajamuna Rural Municipality", "गङ्गाजमुना गाउँपालिका", "rural", 7),
                ("Jwalamukhi Rural Municipality", "ज्वालामुखी गाउँपालिका", "rural", 6),
                ("Khaniyabash Rural Municipality", "खनियाबास गाउँपालिका", "rural", 7),
                ("Netrawati Dabjong Rural Municipality", "नेत्रावती डबजोङ गाउँपालिका", "rural", 6),
                ("Rubi Valley Rural Municipality", "रुबी भ्याली गाउँपालिका", "rural", 6),
                ("Siddhalek Rural Municipality", "सिद्धलेक गाउँपालिका", "rural", 6),
                ("Thakre Rural Municipality", "ठाकरे गाउँपालिका", "rural", 7),
                ("Tripura Sundari Rural Municipality", "त्रिपुरासुन्दरी गाउँपालिका", "rural", 7),
            ]},
            "Sindhupalchok": {"name_np": "सिन्धुपाल्चोक", "municipalities": [
                ("Chautara Sangachokgadhi Municipality", "चौतारा साँगाचोकगढी नगरपालिका", "municipality", 9),
                ("Melamchi Municipality", "मेलम्ची नगरपालिका", "municipality", 9),
                ("Bahrabise Municipality", "बाह्रबिसे नगरपालिका", "municipality", 9),
                ("Indrawati Rural Municipality", "इन्द्रावती गाउँपालिका", "rural", 7),
                ("Jugal Rural Municipality", "जुगल गाउँपालिका", "rural", 7),
                ("Balefi Rural Municipality", "बालेफी गाउँपालिका", "rural", 6),
                ("Lisankhu Pakhar Rural Municipality", "लिसङ्खु पाखर गाउँपालिका", "rural", 6),
                ("Tripurasundari Rural Municipality", "त्रिपुरासुन्दरी गाउँपालिका", "rural", 6),
                ("Sunkoshi Rural Municipality", "सुनकोशी गाउँपालिका", "rural", 7),
                ("Helambu Rural Municipality", "हेलम्बु गाउँपालिका", "rural", 7),
                ("Bhotekoshi Rural Municipality", "भोटेकोशी गाउँपालिका", "rural", 7),
            ]},
            "Dolakha": {"name_np": "दोलखा", "municipalities": [
                ("Bhimeshwor Municipality", "भीमेश्वर नगरपालिका", "municipality", 10),
                ("Jiri Municipality", "जिरी नगरपालिका", "municipality", 9),
                ("Kalinchok Rural Municipality", "कालिञ्चोक गाउँपालिका", "rural", 6),
                ("Baiteshwor Rural Municipality", "बैतेश्वर गाउँपालिका", "rural", 6),
                ("Bigu Rural Municipality", "बिगु गाउँपालिका", "rural", 6),
                ("Gaurishankar Rural Municipality", "गौरीशंकर गाउँपालिका", "rural", 7),
                ("Melung Rural Municipality", "मेलुङ गाउँपालिका", "rural", 6),
                ("Sailung Rural Municipality", "शैलुङ गाउँपालिका", "rural", 6),
                ("Tamakoshi Rural Municipality", "तामाकोशी गाउँपालिका", "rural", 7),
            ]},
            "Ramechhap": {"name_np": "रामेछाप", "municipalities": [
                ("Manthali Municipality", "मन्थली नगरपालिका", "municipality", 9),
                ("Ramechhap Municipality", "रामेछाप नगरपालिका", "municipality", 9),
                ("Doramba Rural Municipality", "दोरम्बा गाउँपालिका", "rural", 6),
                ("Gokulganga Rural Municipality", "गोकुलगंगा गाउँपालिका", "rural", 6),
                ("Khandadevi Rural Municipality", "खाँडादेवी गाउँपालिका", "rural", 7),
                ("Likhu Tamakoshi Rural Municipality", "लिखु तामाकोशी गाउँपालिका", "rural", 6),
                ("Sunapati Rural Municipality", "सुनापती गाउँपालिका", "rural", 6),
                ("Umakunda Rural Municipality", "उमाकुण्ड गाउँपालिका", "rural", 6),
            ]},
            "Sindhuli": {"name_np": "सिन्धुली", "municipalities": [
                ("Kamalamai Municipality", "कमलामाई नगरपालिका", "municipality", 9),
                ("Dudhauli Municipality", "दुधौली नगरपालिका", "municipality", 9),
                ("Sunkoshi Rural Municipality", "सुनकोशी गाउँपालिका", "rural", 6),
                ("Golanjor Rural Municipality", "गोलन्जर गाउँपालिका", "rural", 6),
                ("Hariharpurgadhi Rural Municipality", "हरिहरपुरगढी गाउँपालिका", "rural", 6),
                ("Marin Rural Municipality", "मरिण गाउँपालिका", "rural", 6),
                ("Phikkal Rural Municipality", "फिक्कल गाउँपालिका", "rural", 6),
                ("Tinpatan Rural Municipality", "तीनपाटन गाउँपालिका", "rural", 6),
            ]},
        }
    },
    "Gandaki Province": {
        "name_np": "गण्डकी प्रदेश",
        "districts": {
            "Kaski": {"name_np": "कास्की", "municipalities": [
                ("Pokhara Metropolitan City", "पोखरा महानगरपालिका", "metropolitan", 33),
                ("Annapurna Rural Municipality", "अन्नपूर्ण गाउँपालिका", "rural", 6),
                ("Machhapuchchhre Rural Municipality", "माछापुछ्रे गाउँपालिका", "rural", 6),
                ("Madi Rural Municipality", "माडी गाउँपालिका", "rural", 6),
                ("Rupa Rural Municipality", "रूपा गाउँपालिका", "rural", 6),
            ]},
            "Tanahun": {"name_np": "तनहुँ", "municipalities": [
                ("Bhimad Municipality", "भिमाद नगरपालिका", "municipality", 9),
                ("Byas Municipality", "व्यास नगरपालिका", "municipality", 12),
                ("Shuklagandaki Municipality", "शुक्लागण्डकी नगरपालिका", "municipality", 9),
                ("Amarapuri Rural Municipality", "अमरपुरी गाउँपालिका", "rural", 6),
                ("Anbukhaireni Rural Municipality", "आँबुखैरेनी गाउँपालिका", "rural", 6),
                ("Bandipur Rural Municipality", "बन्दीपुर गाउँपालिका", "rural", 6),
                ("Ghiring Rural Municipality", "घिरिङ गाउँपालिका", "rural", 6),
                ("Myagde Rural Municipality", "म्याग्दे गाउँपालिका", "rural", 6),
                ("Rhishing Rural Municipality", "ऋषिङ गाउँपालिका", "rural", 6),
                ("Devghat Rural Municipality", "देवघाट गाउँपालिका", "rural", 6),
            ]},
            "Syangja": {"name_np": "स्याङ्जा", "municipalities": [
                ("Waling Municipality", "वालिङ नगरपालिका", "municipality", 9),
                ("Galyang Municipality", "गल्याङ नगरपालिका", "municipality", 9),
                ("Putalibazar Municipality", "पुतलीबजार नगरपालिका", "municipality", 11),
                ("Bhirkot Municipality", "भीरकोट नगरपालिका", "municipality", 9),
                ("Arjunchaupari Rural Municipality", "अर्जुनचौपारी गाउँपालिका", "rural", 6),
                ("Biruwa Rural Municipality", "बिरुवा गाउँपालिका", "rural", 6),
                ("Aandhikhola Rural Municipality", "आँधीखोला गाउँपालिका", "rural", 6),
                ("Harinas Rural Municipality", "हरिनास गाउँपालिका", "rural", 6),
                ("Kaligandaki Rural Municipality", "कालीगण्डकी गाउँपालिका", "rural", 6),
                ("Phedikhola Rural Municipality", "फेदीखोला गाउँपालिका", "rural", 6),
            ]},
            "Gorkha": {"name_np": "गोर्खा", "municipalities": [
                ("Gorkha Municipality", "गोर्खा नगरपालिका", "municipality", 14),
                ("Palungtar Municipality", "पालुङटार नगरपालिका", "municipality", 9),
                ("Arughat Rural Municipality", "आरुघाट गाउँपालिका", "rural", 6),
                ("Ajirkot Rural Municipality", "अजिरकोट गाउँपालिका", "rural", 6),
                ("Barpak Sulikot Rural Municipality", "बारपाक सुलीकोट गाउँपालिका", "rural", 6),
                ("Bhimsen Rural Municipality", "भिमसेन गाउँपालिका", "rural", 6),
                ("Chum Nubri Rural Municipality", "चुम नुब्री गाउँपालिका", "rural", 5),
                ("Dharche Rural Municipality", "धार्चे गाउँपालिका", "rural", 5),
                ("Gandaki Rural Municipality", "गण्डकी गाउँपालिका", "rural", 5),
                ("Sahid Lakhan Rural Municipality", "शहीद लखन गाउँपालिका", "rural", 6),
                ("Siranchok Rural Municipality", "सिरानचोक गाउँपालिका", "rural", 6),
                ("Tsum Nubri Rural Municipality", "त्सुम नुब्री गाउँपालिका", "rural", 5),
            ]},
            "Lamjung": {"name_np": "लमजुङ", "municipalities": [
                ("Besishahar Municipality", "बेसीशहर नगरपालिका", "municipality", 10),
                ("Madhya Nepal Municipality", "मध्यनेपाल नगरपालिका", "municipality", 9),
                ("Rainas Municipality", "रायनास नगरपालिका", "municipality", 9),
                ("Dordi Rural Municipality", "दोर्दी गाउँपालिका", "rural", 6),
                ("Dudhpokhari Rural Municipality", "दूधपोखरी गाउँपालिका", "rural", 6),
                ("Kwholasothar Rural Municipality", "क्व्होलासोथर गाउँपालिका", "rural", 6),
                ("Marsyangdi Rural Municipality", "मर्स्याङ्दी गाउँपालिका", "rural", 6),
                ("Sundarbazar Municipality", "सुन्दरबजार नगरपालिका", "municipality", 9),
            ]},
            "Manang": {"name_np": "मनाङ", "municipalities": [
                ("Chame Rural Municipality", "चामे गाउँपालिका", "rural", 4),
                ("Narphu Rural Municipality", "नार्फु गाउँपालिका", "rural", 4),
                ("Nasho Rural Municipality", "नासो गाउँपालिका", "rural", 4),
                ("Manang Disyang Rural Municipality", "मनाङ डिसयाङ गाउँपालिका", "rural", 4),
            ]},
            "Mustang": {"name_np": "मुस्ताङ", "municipalities": [
                ("Mustang Rural Municipality", "मुस्ताङ गाउँपालिका", "rural", 5),
                ("Dalome Rural Municipality", "डालोमे गाउँपालिका", "rural", 5),
                ("Gharapjhong Rural Municipality", "घरपझोङ गाउँपालिका", "rural", 5),
                ("Lomanthang Rural Municipality", "लोमन्थाङ गाउँपालिका", "rural", 5),
                ("Thasang Rural Municipality", "थासाङ गाउँपालिका", "rural", 5),
            ]},
            "Myagdi": {"name_np": "म्याग्दी", "municipalities": [
                ("Beni Municipality", "बेनी नगरपालिका", "municipality", 9),
                ("Annapurna Rural Municipality", "अन्नपूर्ण गाउँपालिका", "rural", 5),
                ("Dhaulagiri Rural Municipality", "धौलागिरी गाउँपालिका", "rural", 5),
                ("Mangala Rural Municipality", "मङ्गला गाउँपालिका", "rural", 6),
                ("Malika Rural Municipality", "मालिका गाउँपालिका", "rural", 6),
                ("Raghuganga Rural Municipality", "रघुगंगा गाउँपालिका", "rural", 6),
            ]},
            "Baglung": {"name_np": "बाग्लुङ", "municipalities": [
                ("Baglung Municipality", "बागलुङ नगरपालिका", "municipality", 14),
                ("Dhorpatan Municipality", "ढोरपाटन नगरपालिका", "municipality", 9),
                ("Jaimini Municipality", "जैमिनी नगरपालिका", "municipality", 11),
                ("Bareng Rural Municipality", "बरेङ गाउँपालिका", "rural", 6),
                ("Badigad Rural Municipality", "बडिगाड गाउँपालिका", "rural", 7),
                ("Kanthekhola Rural Municipality", "काठेखोला गाउँपालिका", "rural", 6),
                ("Nisikhola Rural Municipality", "निसीखोला गाउँपालिका", "rural", 7),
                ("Taman Khola Rural Municipality", "तमानखोला गाउँपालिका", "rural", 5),
                ("Tara Khola Rural Municipality", "ताराखोला गाउँपालिका", "rural", 6),
            ]},
            "Parbat": {"name_np": "पर्वत", "municipalities": [
                ("Kushma Municipality", "कुश्मा नगरपालिका", "municipality", 9),
                ("Phalewas Municipality", "फलेवास नगरपालिका", "municipality", 11),
                ("Bihadi Rural Municipality", "बिहादी गाउँपालिका", "rural", 6),
                ("Jaljala Rural Municipality", "जलजला गाउँपालिका", "rural", 6),
                ("Modi Rural Municipality", "मोदी गाउँपालिका", "rural", 6),
                ("Mahashila Rural Municipality", "महाशिला गाउँपालिका", "rural", 6),
                ("Painyu Rural Municipality", "पैंयू गाउँपालिका", "rural", 6),
            ]},
            "Nawalpur": {"name_np": "नवलपुर", "municipalities": [
                ("Kawasoti Municipality", "कावासोती नगरपालिका", "municipality", 13),
                ("Bulingtar Rural Municipality", "बुलिङटार गाउँपालिका", "rural", 6),
                ("Devchuli Municipality", "देवचुली नगरपालिका", "municipality", 11),
                ("Gaindakot Municipality", "गैंडाकोट नगरपालिका", "municipality", 10),
                ("Hupsekot Municipality", "हुप्सेकोट नगरपालिका", "municipality", 10),
                ("Madhyabindu Municipality", "मध्यविन्दु नगरपालिका", "municipality", 10),
                ("Binayee Triveni Rural Municipality", "विनायी त्रिवेणी गाउँपालिका", "rural", 6),
                ("Baudikhola Rural Municipality", "बौदीखोला गाउँपालिका", "rural", 6),
            ]},
        }
    },
    "Lumbini Province": {
        "name_np": "लुम्बिनी प्रदेश",
        "districts": {
            "Rupandehi": {"name_np": "रुपन्देही", "municipalities": [
                ("Butwal Sub-Metropolitan City", "बुटवल उपमहानगरपालिका", "sub_metropolitan", 19),
                ("Siddharthanagar Municipality", "सिद्धार्थनगर नगरपालिका", "municipality", 17),
                ("Devdaha Municipality", "देवदह नगरपालिका", "municipality", 9),
                ("Lumbini Sanskritik Municipality", "लुम्बिनी सांस्कृतिक नगरपालिका", "municipality", 9),
                ("Marchawari Rural Municipality", "मर्चवारी गाउँपालिका", "rural", 6),
                ("Omsatiya Rural Municipality", "ओमसतिया गाउँपालिका", "rural", 6),
                ("Rohini Rural Municipality", "रोहिणी गाउँपालिका", "rural", 6),
                ("Sammarimai Rural Municipality", "सम्मरीमाई गाउँपालिका", "rural", 6),
                ("Shuddhhodhan Rural Municipality", "शुद्धोधन गाउँपालिका", "rural", 6),
                ("Siyari Rural Municipality", "सियारी गाउँपालिका", "rural", 6),
                ("Tillotama Municipality", "तिलोत्तमा नगरपालिका", "municipality", 16),
                ("Gaidahawa Rural Municipality", "गैडहवा गाउँपालिका", "rural", 6),
                ("Kotahimai Rural Municipality", "कोटहीमाई गाउँपालिका", "rural", 6),
                ("Mayadevi Rural Municipality", "मायादेवी गाउँपालिका", "rural", 6),
                ("Sainamaina Municipality", "सैनामैना नगरपालिका", "municipality", 9),
            ]},
            "Kapilvastu": {"name_np": "कपिलवस्तु", "municipalities": [
                ("Kapilvastu Municipality", "कपिलवस्तु नगरपालिका", "municipality", 9),
                ("Buddhabhumi Municipality", "बुद्धभूमि नगरपालिका", "municipality", 9),
                ("Maharajgunj Municipality", "महाराजगञ्ज नगरपालिका", "municipality", 9),
                ("Shivaraj Municipality", "शिवराज नगरपालिका", "municipality", 11),
                ("Banganga Municipality", "बाणगंगा नगरपालिका", "municipality", 9),
                ("Krishnanagar Municipality", "कृष्णनगर नगरपालिका", "municipality", 9),
                ("Bijayanagar Rural Municipality", "विजयनगर गाउँपालिका", "rural", 6),
                ("Mayadevi Rural Municipality", "मायादेवी गाउँपालिका", "rural", 5),
                ("Suddhodhan Rural Municipality", "शुद्धोधन गाउँपालिका", "rural", 6),
                ("Yasodhara Rural Municipality", "यशोधरा गाउँपालिका", "rural", 6),
            ]},
            "Nawalparasi": {"name_np": "नवलपरासी", "municipalities": [
                ("Sunwal Municipality", "सुनवल नगरपालिका", "municipality", 9),
                ("Palhinandan Rural Municipality", "पाल्हीनन्दन गाउँपालिका", "rural", 6),
                ("Pratappur Rural Municipality", "प्रतापपुर गाउँपालिका", "rural", 6),
                ("Sarawal Rural Municipality", "सरावल गाउँपालिका", "rural", 6),
                ("Susta Rural Municipality", "सुस्ता गाउँपालिका", "rural", 5),
            ]},
            "Arghakhanchi": {"name_np": "अर्घाखाँची", "municipalities": [
                ("Sandhikharka Municipality", "सन्धिखर्क नगरपालिका", "municipality", 9),
                ("Sitganga Municipality", "सितगङ्गा नगरपालिका", "municipality", 9),
                ("Bhumikasthan Municipality", "भूमिकास्थान नगरपालिका", "municipality", 9),
                ("Chhatradev Rural Municipality", "छत्रदेव गाउँपालिका", "rural", 7),
                ("Malarani Rural Municipality", "मालारानी गाउँपालिका", "rural", 6),
                ("Panini Rural Municipality", "पाणिनी गाउँपालिका", "rural", 6),
            ]},
            "Gulmi": {"name_np": "गुल्मी", "municipalities": [
                ("Musikot Municipality", "मुसिकोट नगरपालिका", "municipality", 9),
                ("Resunga Municipality", "रेसुङ्गा नगरपालिका", "municipality", 9),
                ("Chandrakot Rural Municipality", "चन्द्रकोट गाउँपालिका", "rural", 6),
                ("Chatrakot Rural Municipality", "छत्रकोट गाउँपालिका", "rural", 6),
                ("Dhurkot Rural Municipality", "धुर्कोट गाउँपालिका", "rural", 6),
                ("Gulmi Darbar Rural Municipality", "गुल्मी दरबार गाउँपालिका", "rural", 7),
                ("Isma Rural Municipality", "इस्मा गाउँपालिका", "rural", 6),
                ("Kaligandaki Rural Municipality", "कालीगण्डकी गाउँपालिका", "rural", 6),
                ("Madane Rural Municipality", "मदाने गाउँपालिका", "rural", 6),
                ("Malika Rural Municipality", "मालिका गाउँपालिका", "rural", 6),
                ("Ruru Rural Municipality", "रुरु गाउँपालिका", "rural", 6),
                ("Satyawati Rural Municipality", "सत्यवती गाउँपालिका", "rural", 7),
            ]},
            "Palpa": {"name_np": "पाल्पा", "municipalities": [
                ("Tansen Municipality", "तानसेन नगरपालिका", "municipality", 9),
                ("Rampur Municipality", "रामपुर नगरपालिका", "municipality", 9),
                ("Ribdikot Rural Municipality", "रिब्दीकोट गाउँपालिका", "rural", 6),
                ("Bagnaskali Rural Municipality", "बगनासकाली गाउँपालिका", "rural", 6),
                ("Mathagadhi Rural Municipality", "माथागढी गाउँपालिका", "rural", 6),
                ("Nisdi Rural Municipality", "निस्दी गाउँपालिका", "rural", 6),
                ("Purbakhola Rural Municipality", "पूर्वखोला गाउँपालिका", "rural", 6),
                ("Rainadevi Chhahara Rural Municipality", "रैनादेवी छहरा गाउँपालिका", "rural", 6),
                ("Rambha Rural Municipality", "रम्भा गाउँपालिका", "rural", 6),
                ("Tinau Rural Municipality", "तिनाउ गाउँपालिका", "rural", 6),
            ]},
            "Pyuthan": {"name_np": "प्युठान", "municipalities": [
                ("Pyuthan Municipality", "प्युठान नगरपालिका", "municipality", 9),
                ("Swargadwari Municipality", "स्वर्गद्वारी नगरपालिका", "municipality", 9),
                ("Airawati Rural Municipality", "ऐरावती गाउँपालिका", "rural", 6),
                ("Gaumukhi Rural Municipality", "गौमुखी गाउँपालिका", "rural", 6),
                ("Jhimruk Rural Municipality", "झिमरुक गाउँपालिका", "rural", 7),
                ("Lungri Rural Municipality", "लुङ्री गाउँपालिका", "rural", 6),
                ("Mallarani Rural Municipality", "मल्लरानी गाउँपालिका", "rural", 6),
                ("Mandavi Rural Municipality", "माण्डवी गाउँपालिका", "rural", 6),
                ("Naubahini Rural Municipality", "नौबहिनी गाउँपालिका", "rural", 7),
                ("Sarumarani Rural Municipality", "सरुमारानी गाउँपालिका", "rural", 5),
            ]},
            "Rolpa": {"name_np": "रोल्पा", "municipalities": [
                ("Rolpa Municipality", "रोल्पा नगरपालिका", "municipality", 9),
                ("Triveni Rural Municipality", "त्रिवेणी गाउँपालिका", "rural", 6),
                ("Thawang Rural Municipality", "थवाङ गाउँपालिका", "rural", 6),
                ("Lungri Rural Municipality", "लुङ्री गाउँपालिका", "rural", 6),
                ("Madi Rural Municipality", "माडी गाउँपालिका", "rural", 6),
                ("Pariwartan Rural Municipality", "परिवर्तन गाउँपालिका", "rural", 6),
                ("Runtigadhi Rural Municipality", "रुन्टीगढी गाउँपालिका", "rural", 6),
                ("Sunchhahari Rural Municipality", "सुनछहरी गाउँपालिका", "rural", 6),
                ("Sunil Smriti Rural Municipality", "सुनिल स्मृति गाउँपालिका", "rural", 6),
                ("Duikholi Rural Municipality", "दुई खोली गाउँपालिका", "rural", 6),
            ]},
            "Eastern Rukum": {"name_np": "पूर्वी रुकुम", "municipalities": [
                ("Bhume Rural Municipality", "भूमे गाउँपालिका", "rural", 5),
                ("Putha Uttarganga Rural Municipality", "पुथा उत्तरगंगा गाउँपालिका", "rural", 5),
                ("Sisne Rural Municipality", "सिस्ने गाउँपालिका", "rural", 5),
            ]},
            "Dang": {"name_np": "दाङ", "municipalities": [
                ("Tulsipur Sub-Metropolitan City", "तुलसीपुर उपमहानगरपालिका", "sub_metropolitan", 19),
                ("Ghorahi Sub-Metropolitan City", "घोराही उपमहानगरपालिका", "sub_metropolitan", 19),
                ("Lamahi Municipality", "लमही नगरपालिका", "municipality", 9),
                ("Banglachuli Rural Municipality", "बंगलाचुली गाउँपालिका", "rural", 6),
                ("Babai Rural Municipality", "बबई गाउँपालिका", "rural", 6),
                ("Dangisharan Rural Municipality", "दंगीशरण गाउँपालिका", "rural", 6),
                ("Rajpur Rural Municipality", "राजपुर गाउँपालिका", "rural", 6),
                ("Rapti Rural Municipality", "राप्ती गाउँपालिका", "rural", 6),
                ("Shantinagar Rural Municipality", "शान्तिनगर गाउँपालिका", "rural", 6),
                ("Gadhawa Rural Municipality", "गढवा गाउँपालिका", "rural", 7),
            ]},
            "Banke": {"name_np": "बाँके", "municipalities": [
                ("Nepalgunj Sub-Metropolitan City", "नेपालगञ्ज उपमहानगरपालिका", "sub_metropolitan", 18),
                ("Kohalpur Municipality", "कोहलपुर नगरपालिका", "municipality", 11),
                ("Narainapur Rural Municipality", "नरैनापुर गाउँपालिका", "rural", 6),
                ("Baijanath Rural Municipality", "बैजनाथ गाउँपालिका", "rural", 6),
                ("Duduwa Rural Municipality", "दुदुवा गाउँपालिका", "rural", 5),
                ("Janaki Rural Municipality", "जानकी गाउँपालिका", "rural", 6),
                ("Khajura Rural Municipality", "खजुरा गाउँपालिका", "rural", 6),
                ("Rapti Sonari Rural Municipality", "राप्ती सोनारी गाउँपालिका", "rural", 7),
            ]},
            "Bardiya": {"name_np": "बर्दिया", "municipalities": [
                ("Gulariya Municipality", "गुलरिया नगरपालिका", "municipality", 11),
                ("Madhuwan Municipality", "मधुवन नगरपालिका", "municipality", 9),
                ("Rajapur Municipality", "राजापुर नगरपालिका", "municipality", 9),
                ("Barbardiya Municipality", "बारबर्दिया नगरपालिका", "municipality", 9),
                ("Badhaiyatal Rural Municipality", "बढैयाताल गाउँपालिका", "rural", 7),
                ("Bansgadhi Municipality", "बाँसगढी नगरपालिका", "municipality", 9),
                ("Geruwa Rural Municipality", "गेरुवा गाउँपालिका", "rural", 6),
                ("Thakurbaba Municipality", "ठाकुरबाबा नगरपालिका", "municipality", 9),
            ]},
        }
    },
    "Karnali Province": {
        "name_np": "कर्णाली प्रदेश",
        "districts": {
            "Surkhet": {"name_np": "सुर्खेत", "municipalities": [
                ("Birendranagar Municipality", "वीरेन्द्रनगर नगरपालिका", "municipality", 11),
                ("Bheriganga Municipality", "भेरीगंगा नगरपालिका", "municipality", 11),
                ("Panchapuri Municipality", "पञ्चपुरी नगरपालिका", "municipality", 10),
                ("Gurtu Rural Municipality", "गुर्तु गाउँपालिका", "rural", 6),
                ("Chaukune Rural Municipality", "चौकुने गाउँपालिका", "rural", 5),
                ("Barahtal Rural Municipality", "बराहताल गाउँपालिका", "rural", 6),
                ("Simta Rural Municipality", "सिम्ता गाउँपालिका", "rural", 6),
                ("Lekbeshi Municipality", "लेकबेशी नगरपालिका", "municipality", 9),
                ("Chingad Rural Municipality", "चिङ्गाड गाउँपालिका", "rural", 5),
            ]},
            "Dailekh": {"name_np": "दैलेख", "municipalities": [
                ("Narayan Municipality", "नारायण नगरपालिका", "municipality", 9),
                ("Dullu Municipality", "डुल्लु नगरपालिका", "municipality", 9),
                ("Aathabis Municipality", "आठबिस नगरपालिका", "municipality", 9),
                ("Bhairabi Rural Municipality", "भैरवी गाउँपालिका", "rural", 6),
                ("Dungeshwar Rural Municipality", "डुंगेश्वर गाउँपालिका", "rural", 6),
                ("Gurans Rural Municipality", "गुराँस गाउँपालिका", "rural", 6),
                ("Mahabu Rural Municipality", "महाबु गाउँपालिका", "rural", 7),
                ("Naumule Rural Municipality", "नौमुले गाउँपालिका", "rural", 5),
                ("Thantikandh Rural Municipality", "ठाँटीकाँध गाउँपालिका", "rural", 6),
                ("Chamunda Bindrasaini Municipality", "चामुण्डा विन्द्रासैनी नगरपालिका", "municipality", 9),
            ]},
            "Jajarkot": {"name_np": "जाजरकोट", "municipalities": [
                ("Bheri Municipality", "भेरी नगरपालिका", "municipality", 9),
                ("Chhedagad Municipality", "छेडागाड नगरपालिका", "municipality", 9),
                ("Barekot Rural Municipality", "बारेकोट गाउँपालिका", "rural", 6),
                ("Junichande Rural Municipality", "जुनीचाँदे गाउँपालिका", "rural", 6),
                ("Kuse Rural Municipality", "कुसे गाउँपालिका", "rural", 6),
                ("Nalgad Municipality", "नलगाड नगरपालिका", "municipality", 9),
                ("Shiwalaya Rural Municipality", "शिवालय गाउँपालिका", "rural", 7),
            ]},
            "Western Rukum": {"name_np": "पश्चिम रुकुम", "municipalities": [
                ("Musikot Municipality", "मुसिकोट नगरपालिका", "municipality", 9),
                ("Aathbiskot Municipality", "आठबिसकोट नगरपालिका", "municipality", 9),
                ("Banfikot Rural Municipality", "बाँफिकोट गाउँपालिका", "rural", 6),
                ("Chaurjahari Municipality", "चौरजहारी नगरपालिका", "municipality", 9),
                ("Triveni Rural Municipality", "त्रिवेणी गाउँपालिका", "rural", 5),
            ]},
            "Salyan": {"name_np": "सल्यान", "municipalities": [
                ("Sharada Municipality", "शारदा नगरपालिका", "municipality", 9),
                ("Bagchaur Municipality", "बागचौर नगरपालिका", "municipality", 9),
                ("Bangad Kupinde Municipality", "बनगाड कुपिण्डे नगरपालिका", "municipality", 9),
                ("Kalimati Rural Municipality", "कालीमाटी गाउँपालिका", "rural", 6),
                ("Darma Rural Municipality", "दार्मा गाउँपालिका", "rural", 6),
                ("Kapurkot Rural Municipality", "कपुरकोट गाउँपालिका", "rural", 7),
                ("Kumakh Rural Municipality", "कुमाख गाउँपालिका", "rural", 6),
                ("Siddha Kumakh Rural Municipality", "सिद्ध कुमाख गाउँपालिका", "rural", 6),
                ("Tribeni Rural Municipality", "त्रिवेणी गाउँपालिका", "rural", 6),
            ]},
            "Dolpa": {"name_np": "डोल्पा", "municipalities": [
                ("Thuli Bheri Municipality", "ठूली भेरी नगरपालिका", "municipality", 9),
                ("Tripurasundari Municipality", "त्रिपुरासुन्दरी नगरपालिका", "municipality", 9),
                ("Dolpo Buddha Rural Municipality", "डोल्पो बुद्ध गाउँपालिका", "rural", 5),
                ("Jagdulla Rural Municipality", "जगदुल्ला गाउँपालिका", "rural", 5),
                ("Kaike Rural Municipality", "काईके गाउँपालिका", "rural", 5),
                ("Mudkechula Rural Municipality", "मुड्केचुला गाउँपालिका", "rural", 5),
                ("She Phoksundo Rural Municipality", "शे फोक्सुन्डो गाउँपालिका", "rural", 5),
                ("Chharka Tangsong Rural Municipality", "छार्का ताङसोङ गाउँपालिका", "rural", 4),
            ]},
            "Humla": {"name_np": "हुम्ला", "municipalities": [
                ("Simkot Rural Municipality", "सिमकोट गाउँपालिका", "rural", 6),
                ("Adanchuli Rural Municipality", "अदानचुली गाउँपालिका", "rural", 5),
                ("Chankheli Rural Municipality", "चंखेली गाउँपालिका", "rural", 5),
                ("Kharpunath Rural Municipality", "खार्पुनाथ गाउँपालिका", "rural", 5),
                ("Namkha Rural Municipality", "नाम्खा गाउँपालिका", "rural", 6),
                ("Sarkegad Rural Municipality", "सर्केगाड गाउँपालिका", "rural", 6),
                ("Tanjakot Rural Municipality", "ताँजाकोट गाउँपालिका", "rural", 5),
            ]},
            "Jumla": {"name_np": "जुम्ला", "municipalities": [
                ("Chandannath Municipality", "चन्दननाथ नगरपालिका", "municipality", 9),
                ("Guthichaur Rural Municipality", "गुठिचौर गाउँपालिका", "rural", 5),
                ("Hima Rural Municipality", "हिमा गाउँपालिका", "rural", 5),
                ("Kanaka Sundari Rural Municipality", "कनकासुन्दरी गाउँपालिका", "rural", 5),
                ("Patarasi Rural Municipality", "पतारासी गाउँपालिका", "rural", 5),
                ("Sinja Rural Municipality", "सिञ्जा गाउँपालिका", "rural", 5),
                ("Tatopani Rural Municipality", "तातोपानी गाउँपालिका", "rural", 5),
                ("Tila Rural Municipality", "तिला गाउँपालिका", "rural", 6),
            ]},
            "Kalikot": {"name_np": "कालिकोट", "municipalities": [
                ("Khandachakra Municipality", "खाँडाचक्र नगरपालिका", "municipality", 9),
                ("Raskot Municipality", "रास्कोट नगरपालिका", "municipality", 9),
                ("Tilagufa Municipality", "तिलागुफा नगरपालिका", "municipality", 9),
                ("Pachaljharana Rural Municipality", "पचालझरना गाउँपालिका", "rural", 6),
                ("Palata Rural Municipality", "पलाँता गाउँपालिका", "rural", 5),
                ("Mahawai Rural Municipality", "महावाई गाउँपालिका", "rural", 5),
                ("Narharinath Rural Municipality", "नरहरिनाथ गाउँपालिका", "rural", 6),
                ("Shubha Kalika Rural Municipality", "शुभकालिका गाउँपालिका", "rural", 5),
            ]},
            "Mugu": {"name_np": "मुगु", "municipalities": [
                ("Chhayanath Rara Municipality", "छायाँनाथ रारा नगरपालिका", "municipality", 9),
                ("Mugum Karmarong Rural Municipality", "मुगुम कार्मारोङ गाउँपालिका", "rural", 5),
                ("Khatyad Rural Municipality", "खत्याड गाउँपालिका", "rural", 5),
                ("Soru Rural Municipality", "सोरु गाउँपालिका", "rural", 5),
            ]},
        }
    },
    "Sudurpashchim Province": {
        "name_np": "सुदूरपश्चिम प्रदेश",
        "districts": {
            "Kailali": {"name_np": "कैलाली", "municipalities": [
                ("Dhangadhi Sub-Metropolitan City", "धनगढी उपमहानगरपालिका", "sub_metropolitan", 19),
                ("Tikapur Municipality", "टीकापुर नगरपालिका", "municipality", 9),
                ("Bhajani Municipality", "भजनी नगरपालिका", "municipality", 9),
                ("Gauriganga Municipality", "गौरीगंगा नगरपालिका", "municipality", 9),
                ("Godawari Municipality", "गोदावरी नगरपालिका", "municipality", 11),
                ("Joshipur Rural Municipality", "जोशीपुर गाउँपालिका", "rural", 6),
                ("Kailari Rural Municipality", "कैलारी गाउँपालिका", "rural", 8),
                ("Bardagoriya Rural Municipality", "बर्दगोरिया गाउँपालिका", "rural", 7),
                ("Chure Rural Municipality", "चुरे गाउँपालिका", "rural", 6),
                ("Janaki Rural Municipality", "जानकी गाउँपालिका", "rural", 9),
                ("Lamki Chuha Municipality", "लम्की चुहा नगरपालिका", "municipality", 9),
                ("Mohanyal Rural Municipality", "मोहन्याल गाउँपालिका", "rural", 7),
                ("Phatepur Rural Municipality", "फतेपुर गाउँपालिका", "rural", 6),
            ]},
            "Kanchanpur": {"name_np": "कञ्चनपुर", "municipalities": [
                ("Bhimdatta Municipality", "भीमदत्त नगरपालिका", "municipality", 16),
                ("Punarbas Municipality", "पुनर्वास नगरपालिका", "municipality", 9),
                ("Belauri Municipality", "बेलौरी नगरपालिका", "municipality", 9),
                ("Krishnapur Municipality", "कृष्णपुर नगरपालिका", "municipality", 9),
                ("Bedkot Municipality", "बेदकोट नगरपालिका", "municipality", 9),
                ("Beldandi Rural Municipality", "बेल्दण्डी गाउँपालिका", "rural", 6),
                ("Shuklaphanta Municipality", "शुक्लाफाँटा नगरपालिका", "municipality", 9),
                ("Laljhadi Rural Municipality", "लालझाडी गाउँपालिका", "rural", 6),
                ("Mahakali Municipality", "महाकाली नगरपालिका", "municipality", 9),
            ]},
            "Doti": {"name_np": "डोटी", "municipalities": [
                ("Dipayal Silgadhi Municipality", "दिपायल सिलगढी नगरपालिका", "municipality", 9),
                ("Shikhar Municipality", "शिखर नगरपालिका", "municipality", 9),
                ("Bogtan Phudsil Rural Municipality", "बोगटान फुड्सिल गाउँपालिका", "rural", 6),
                ("Badikedar Rural Municipality", "बडीकेदार गाउँपालिका", "rural", 5),
                ("K I Singh Rural Municipality", "के आई सिंह गाउँपालिका", "rural", 6),
                ("Purbichauki Rural Municipality", "पूर्वीचौकी गाउँपालिका", "rural", 6),
                ("Sayal Rural Municipality", "सायल गाउँपालिका", "rural", 6),
                ("Aadarsha Rural Municipality", "आदर्श गाउँपालिका", "rural", 5),
            ]},
            "Achham": {"name_np": "अछाम", "municipalities": [
                ("Mangalsen Municipality", "मङ्गलसेन नगरपालिका", "municipality", 9),
                ("Sanphebagar Municipality", "साँफेबगर नगरपालिका", "municipality", 9),
                ("Bannigadhi Jayagadh Rural Municipality", "बान्नीगढी जयगढ गाउँपालिका", "rural", 7),
                ("Chaurpati Rural Municipality", "चौरपाटी गाउँपालिका", "rural", 6),
                ("Dhakari Rural Municipality", "ढकारी गाउँपालिका", "rural", 6),
                ("Kamalbazar Municipality", "कमलबजार नगरपालिका", "municipality", 9),
                ("Mellekh Rural Municipality", "मेल्लेख गाउँपालिका", "rural", 6),
                ("Panchadeval Binayak Rural Municipality", "पञ्चदेवल विनायक गाउँपालिका", "rural", 6),
                ("Ramaroshan Rural Municipality", "रामारोशन गाउँपालिका", "rural", 6),
                ("Turmakhand Rural Municipality", "तुर्माखाँद गाउँपालिका", "rural", 6),
            ]},
            "Bajura": {"name_np": "बाजुरा", "municipalities": [
                ("Badimalika Municipality", "बडीमालिका नगरपालिका", "municipality", 9),
                ("Budhinanda Municipality", "बुढीनन्दा नगरपालिका", "municipality", 9),
                ("Gaumul Rural Municipality", "गौमुल गाउँपालिका", "rural", 6),
                ("Himali Rural Municipality", "हिमाली गाउँपालिका", "rural", 5),
                ("Jagannath Rural Municipality", "जगन्नाथ गाउँपालिका", "rural", 5),
                ("Khaptad Chhanna Rural Municipality", "खप्तड छान्ना गाउँपालिका", "rural", 5),
                ("Kuldevta Rural Municipality", "कुलदेवता गाउँपालिका", "rural", 5),
                ("Swami Kartik Khapar Rural Municipality", "स्वामी कार्तिक खापर गाउँपालिका", "rural", 5),
                ("Triveni Rural Municipality", "त्रिवेणी गाउँपालिका", "rural", 5),
            ]},
            "Bajhang": {"name_np": "बझाङ", "municipalities": [
                ("Bungal Municipality", "बुंगल नगरपालिका", "municipality", 11),
                ("Talkot Municipality", "तल्कोट नगरपालिका", "municipality", 9),
                ("Durgathali Rural Municipality", "दुर्गाथली गाउँपालिका", "rural", 5),
                ("Jayaprithivi Municipality", "जयपृथ्वी नगरपालिका", "municipality", 9),
                ("Kedar Rural Municipality", "केदार गाउँपालिका", "rural", 5),
                ("Khandeshwari Rural Municipality", "खाँडेश्वरी गाउँपालिका", "rural", 5),
                ("Masta Rural Municipality", "मष्टा गाउँपालिका", "rural", 5),
                ("Saipal Rural Municipality", "सैपाल गाउँपालिका", "rural", 5),
                ("Surma Rural Municipality", "सुर्मा गाउँपालिका", "rural", 6),
                ("Thalara Rural Municipality", "थलारा गाउँपालिका", "rural", 5),
                ("Chhanna Rural Municipality", "छान्ना गाउँपालिका", "rural", 5),
            ]},
            "Darchula": {"name_np": "दार्चुला", "municipalities": [
                ("Darchula Municipality", "दार्चुला नगरपालिका", "municipality", 9),
                ("Malikarjun Rural Municipality", "मालिकार्जुन गाउँपालिका", "rural", 6),
                ("Marma Rural Municipality", "मर्मा गाउँपालिका", "rural", 6),
                ("Naugad Rural Municipality", "नौगाड गाउँपालिका", "rural", 5),
                ("Shailyashikhar Municipality", "शैल्यशिखर नगरपालिका", "municipality", 9),
                ("Apihimal Rural Municipality", "अपिहिमाल गाउँपालिका", "rural", 6),
                ("Dunhu Rural Municipality", "दुहुँ गाउँपालिका", "rural", 5),
                ("Lekam Rural Municipality", "लेकम गाउँपालिका", "rural", 5),
            ]},
            "Baitadi": {"name_np": "बैतडी", "municipalities": [
                ("Dasharathchand Municipality", "दशरथचन्द नगरपालिका", "municipality", 9),
                ("Patan Municipality", "पाटन नगरपालिका", "municipality", 9),
                ("Purchaudi Municipality", "पुर्चौडी नगरपालिका", "municipality", 9),
                ("Dogadakedar Rural Municipality", "डोगडाकेदार गाउँपालिका", "rural", 6),
                ("Melauli Municipality", "मेलौली नगरपालिका", "municipality", 9),
                ("Shivanath Rural Municipality", "शिवनाथ गाउँपालिका", "rural", 6),
                ("Surnaya Rural Municipality", "सुर्नया गाउँपालिका", "rural", 6),
                ("Pancheswor Rural Municipality", "पञ्चेश्वर गाउँपालिका", "rural", 6),
                ("Dilasaini Rural Municipality", "दिलासैनी गाउँपालिका", "rural", 6),
            ]},
            "Dadeldhura": {"name_np": "डडेलधुरा", "municipalities": [
                ("Amargadhi Municipality", "अमरगढी नगरपालिका", "municipality", 9),
                ("Parashuram Municipality", "परशुराम नगरपालिका", "municipality", 9),
                ("Aalital Rural Municipality", "आलीताल गाउँपालिका", "rural", 5),
                ("Ajaymeru Rural Municipality", "अजयमेरु गाउँपालिका", "rural", 5),
                ("Bhageshwar Rural Municipality", "भागेश्वर गाउँपालिका", "rural", 5),
                ("Ganyapadhura Rural Municipality", "गन्यापधुरा गाउँपालिका", "rural", 5),
                ("Navadurga Rural Municipality", "नवदुर्गा गाउँपालिका", "rural", 5),
            ]},
        }
    }
}

# =====================
# SEED DATABASE
# =====================
print("🌱 Seeding Nepal Full Data...")
print("=" * 50)

# Clear existing data
Ward.objects.all().delete()
Municipality.objects.all().delete()
District.objects.all().delete()
Province.objects.all().delete()

province_count = 0
district_count = 0
muni_count = 0
ward_count = 0

for province_name, province_data in data.items():
    province_obj = Province.objects.create(
        name=province_name,
        name_np=province_data["name_np"]
    )
    province_count += 1
    print(f"\n✅ Province: {province_name}")

    for district_name, district_data in province_data["districts"].items():
        district_obj = District.objects.create(
            province=province_obj,
            name=district_name,
            name_np=district_data["name_np"]
        )
        district_count += 1

        for muni_data in district_data["municipalities"]:
            muni_name, muni_name_np, muni_type, total_wards = muni_data
            muni_obj = Municipality.objects.create(
                district=district_obj,
                name=muni_name,
                name_np=muni_name_np,
                type=muni_type,
                total_wards=total_wards
            )
            muni_count += 1

            # Auto-generate wards
            for i in range(1, total_wards + 1):
                Ward.objects.create(
                    municipality=muni_obj,
                    ward_number=i
                )
                ward_count += 1

        print(f"   ✓ District: {district_name} — {len(district_data['municipalities'])} municipalities")

print("\n" + "=" * 50)
print("✅ Seed Complete!")
print(f"   Provinces:      {province_count}")
print(f"   Districts:      {district_count}")
print(f"   Municipalities: {muni_count}")
print(f"   Wards:          {ward_count}")